import type { Metadata } from 'next'
import Link from 'next/link'

import { SiteHeader } from '@/app/contact/site-header'
import { SiteFooter } from '@/app/_components/site-footer'
import { APPLICATION_PRIVACY_NOTICE_VERSION, WEBSITE_PRIVACY_NOTICE_VERSION } from '@/lib/privacy'
import styles from './privacy.module.css'

export const metadata: Metadata = { title: 'Privacy notice' }

export default function PrivacyPage() {
  return <><SiteHeader activePath="/privacy" contentId="privacy-main" /><main id="privacy-main" tabIndex={-1} className={styles.page}>
    <article>
      <p className={styles.eyebrow}>Your information</p>
      <h1>Privacy, in plain language.</h1>
      <p className={styles.intro}>How GI Healthcare handles your information when you explore our website, apply for a role or get in touch.</p>
      <p>Last updated <time dateTime="2026-09-26">26 September 2026</time> · Notice version {WEBSITE_PRIVACY_NOTICE_VERSION}</p>
      <nav aria-label="Privacy notice sections" className={styles.contents}><a href="#website-analytics">Website analytics</a><a href="#cookie-choices">Cookies and your choices</a><a href="#recruitment-answers">Recruitment</a><a href="#retention">Retention</a><a href="#privacy-rights">Your rights</a></nav>
      <div className={styles.summary}><strong>The essentials</strong><p>Optional analytics start only with your permission. We do not sell your personal information or use advertising trackers. Applications and contact enquiries are deleted from the live portal within three calendar months. You can change your analytics choice at any time in the <a href="#cookie-choices">cookie choices section below</a>.</p></div>

      <section><h2>Who is responsible?</h2><p>GI Healthcare Industries Limited is the data controller. Our owner administers the recruitment and enquiry inbox. For privacy questions, corrections, a copy of your information, a manual application review or a complaint, use our <Link href="/contact">contact form</Link>. Please do not include identity documents or sensitive information in your first message.</p></section>

      <section id="website-analytics"><h2>Website visits and optional analytics</h2>
        <p>Our website is about autonomous cooking technology. You can browse, contact us and apply without accepting optional analytics. Essential connection and security processing still occurs to deliver and protect the site.</p>
        <p>If you accept <strong>Website analytics</strong>, we measure which public pages are viewed, supported navigation clicks and estimated active time on a page. We also record broad device, browser and operating-system categories, estimated country, region and city where available, and referral category (direct, search, social or other). The owner can see aggregate charts, an approximate-location world map and these details for individual page views, including their time. These help the owner understand interest in the website and improve its content and navigation. Our lawful basis for optional analytics is your consent (UK GDPR Article 6(1)(a)).</p>
        <p>Country, region and city are inferred from connection information by our hosting service. They are estimates, not a visitor’s exact position, and may reflect a VPN, mobile network or proxy. Map markers summarise countries and do not pinpoint people. The hosting service necessarily receives your IP address; <strong>we do not retain full IP addresses in our analytics database</strong>. We do not request GPS, precise coordinates or a street address. Analytics records use a random identifier for an individual page view, not a persistent identity across visits. We record when analytics consent was given and its version alongside those records. We do not connect analytics to your name, enquiry or application, or build a cross-page visitor profile. Removing names and IP addresses does not mean that detailed technical records are guaranteed anonymous, so they remain access-restricted and subject to the safeguards and retention below.</p>
        <p>City, region and operating-system details are collected only after acceptance of analytics version 2, introduced on 17 September 2026. Earlier acceptance does not automatically enable this expanded collection; we ask again. Earlier refusals remain in effect until changed or expired. Historical records keep their original deletion date, and missing details are not reconstructed.</p>
        <p>Analytics excludes the administrator area, form answers, passwords, clipboard content, keystroke values, session recordings and arbitrary URL parameters. We do not copy full referring URLs. Active-time estimates pause for hidden tabs, consent dialogs and idle periods, and are capped at 30 minutes per page. These statistics do not establish who a visitor is or exactly what they read. No analytics is sent before acceptance or after withdrawal. Browser restrictions, declined consent and blocked requests mean the dashboard does not represent every visit.</p>
      </section>

      <section id="cookie-choices"><h2>Cookies, browser storage and your choices</h2>
        <p>The bottom banner offers <strong>Accept</strong>, <strong>Reject</strong> and a settings icon to manage your choices. Accept enables optional website analytics; Reject leaves it off. Website analytics is off by default. Strictly necessary storage is always enabled because it supports security, your requested sign-in and saving your choice; it is not used as a way to enable optional tracking.</p>
        <p>You can change or withdraw your choice here at any time: <a href="#cookie-choices" data-gi-privacy-open="true">Manage cookie choices</a>. Rejecting or switching analytics off stops future optional collection and discards the current in-memory page-view identifier. It does not affect the lawfulness of processing before withdrawal. These controls remain available on this privacy page without requiring you to accept anything.</p>
        <div className={styles.tableWrap}><table><caption>Storage used by this website</caption><thead><tr><th>Item</th><th>Purpose</th><th>Duration</th></tr></thead><tbody>
          <tr><td><code>gi_privacy</code></td><td>Essential first-party cookie containing your analytics choice, time and notice version. It is scoped to this website hostname and is not an advertising identifier.</td><td>180 days; renewed when you save a choice.</td></tr>
          <tr><td>Admin authentication session</td><td>Essential Supabase session tokens in browser session storage, only for administrator sign-in.</td><td>Tab session; the portal also locks after 15 minutes of inactivity.</td></tr>
          <tr><td>Page-view identifier</td><td>Optional, random identifier held in memory after analytics acceptance, to avoid counting updates to the same page view twice.</td><td>Until navigation, reload, withdrawal or closing the page. No persistent visitor-ID cookie.</td></tr>
          <tr><td>Public asset cache</td><td>Browser caching of public site files for delivery and performance; not a store of submitted form answers.</td><td>Managed by your browser and applicable cache headers.</td></tr>
        </tbody></table></div>
        <p>Deleting or blocking the preference cookie may cause the banner to reappear. Choices are browser- and hostname-specific; they do not automatically carry between devices, private browsing sessions or the www and non-www hostnames. We ask again after expiry or when a material change requires new consent. You can also control site storage in your browser.</p>
      </section>

      <section><h2>Applications, enquiries and security</h2>
        <p><strong>Applications:</strong> your chosen role, name, email, LinkedIn profile link, optional portfolio or project link, short work examples, competitions or awards (or that you have none yet), a failure, and a flaw your friends might point out. We also ask for a declaration of existing UK work permission. If relevant, this includes your permission category and acknowledgement of work restrictions. We use these to consider your application, understand whether the role is compatible with your declared permission and contact you. Our basis is taking steps at your request before a possible employment contract (UK GDPR Article 6(1)(b)).</p>
        <p>We also ask whether you are a current student or a graduate. Current students provide their degree and year of study; graduates provide their graduation year. The owner can restrict each role to students, graduates, or both. The application form shows this requirement and prevents online submission if your selected status does not match. You can <Link href="/contact">contact the owner for a human review</Link> to explain your circumstances, correct an answer or contest the outcome. Unsubmitted answers are not saved. We do not calculate or screen by age. Education answers are deleted with the rest of your application; changing a role’s eligibility does not reclassify applications already received.</p>
        <p>We do not ask for a CV, date of birth, share code or identity document at this stage. If we make a conditional offer, we will arrange an appropriate right-to-work check before employment, under our legal obligations (Article 6(1)(c)). That is a separate process with its own information and record-keeping requirements.</p>
        <p><strong>Enquiries:</strong> your name, email, optional phone number and message. We use them to respond and follow up on your enquiry. Our basis is our legitimate interest in communicating with people who contact our business (Article 6(1)(f)).</p>
        <p><strong>Security and administration:</strong> submission time, status, notice version and a pseudonymous anti-abuse identifier derived from your IP address. We use these to operate the inbox, prevent spam and protect the service, based on legitimate interests (Article 6(1)(f)). Our application database removes this identifier after two days. Hosting providers also process technical connection and security data, such as IP addresses and request metadata, under their separate service-log lifecycles.</p>
        <p>Information comes from you and any relevant work you choose to link. Please share only material you have permission to disclose: no confidential defence material, health information, identity documents or unnecessary information about other people.</p>
      </section>

      <section><h2>Role-specific questions</h2><p>The “A little more about you” section may contain job-relevant questions selected by the owner for that role, including written answers, work links, awards or multiple-choice answers. Required and optional fields are marked on the form. We retain the questions shown alongside your submitted answers so later changes to a posting do not change your application. They are used only to assess your application and are deleted with it after three calendar months. Please do not include sensitive personal information or identity documents in these answers.</p></section>
      <section><h2>Your choices and the eligibility questions</h2>
        <p>A LinkedIn profile link is required for the online application; we no longer ask applicants for a phone number. Portfolio links and links within written examples remain optional. Phone numbers on the contact form are optional. Other requested application fields are needed to consider an online application; name, email and message are needed to respond to an enquiry. You can state that you have no awards yet. You can contact us for help or an accessible alternative, including if you do not have a LinkedIn profile. Submitting is not marketing consent and does not enrol you in a future-jobs talent pool.</p>
        <p>The online form stops if you declare that you cannot do the role without our sponsorship. These are simple rules based on your answers, not a Home Office check. No online submission is saved when you stop at that stage. If an answer is wrong, your circumstances need explanation or you disagree, <Link href="/contact">ask the owner for a human review</Link>, explain your circumstances and contest the outcome. You do not need a share code to ask. A human reviews submitted applications; a visa category or citizenship is not a measure of merit.</p>
      </section>

      <section id="recruitment-answers"><h2>Your application answers</h2>
        <p>Recruitment addendum version {APPLICATION_PRIVACY_NOTICE_VERSION}, effective 16 September 2026. We record your education answers, LinkedIn profile link, short answers and award cards, together with the time and version of your application data-use agreement. The owner may open your LinkedIn link to review your professional background; the portal does not automatically fetch, embed or copy your profile. Earlier applications may retain a phone number until their original deletion date. We do not record typing or clipboard contents. If you separately accept website analytics, a visit to the application page can be counted, but answers and applicant identities are excluded. A human reviews applications; there is no automated personality assessment and analytics is not used to rank applicants.</p>
        <p>Please share only information you are comfortable providing. Do not include health details, personal trauma, private information about friends, or confidential material. Earlier applications may contain the additional example and declaration requested by the earlier form. All answers and declarations are deleted with the application under the same three-calendar-month rule below.</p>
      </section>

<section id="interview-bookings"><h2>Interview invitations and bookings</h2><p>When you use our shared booking page or a private interview invitation, we use your name, email address, selected time and booking or cancellation status to arrange a recruitment conversation. Where the invitation is linked to your application, the email must match your application. The owner sees the booking in the private admin calendar. Our basis is taking steps at your request before a possible employment contract (UK GDPR Article 6(1)(b)). Confirming that you have read this information is not marketing consent.</p><p>Private booking links contain a random access token. Keep the link private: anyone with it can see and cancel its booking. We store a hash rather than the original token in the database, exclude booking pages from optional website analytics, and instruct search engines not to index them. The hosting provider still processes the request URL and connection information as part of delivering and securing the service.</p><p>After booking, you can open the supplied Microsoft Teams meeting link and download a calendar file. Opening Teams is optional until you join your meeting and involves Microsoft processing meeting-related information under the organiser’s Microsoft account arrangements. Where email confirmations are enabled, Resend processes your name, email address, meeting time, meeting title and Teams link to send a calendar invitation or cancellation, with a copy to the owner. This is transactional correspondence, not marketing; open/click tracking is not used. Resend stores account data, metadata, logs and API records in the United States even when emails are sent from its Ireland region. This optional service requires an owner-approved international-processing arrangement; it is not a UK-only service. The booking system does not access or synchronise your personal calendar. Calendar imports remain under your control and do not automatically update when a meeting is cancelled or changed.</p><p>For shared bookings we also use a pseudonymous anti-abuse identifier derived from connection information, based on our legitimate interest in protecting availability (Article 6(1)(f)); it is cleared after two days. Unlinked scheduling records and local email-delivery records are deleted within three calendar months of invitation creation. Linked invitations and bookings are deleted with the application at its original deletion date, including earlier deletion by the owner. Cancelled meetings follow the same retention period; cancellation does not extend it. Calendar downloads and any separate email correspondence are not deleted by the portal. The owner must manage those copies separately. Contact us through the contact form for help, corrections or another way to arrange a meeting.</p></section>
      <section id="retention"><h2>How long we keep information</h2>
        <p><strong>Website analytics:</strong> page-view records, activity measurements and their consent timestamps expire after 30 days. They are excluded from reports at expiry and removed by a scheduled deletion task running every minute. Analytics abuse-prevention counters use a changing keyed hash of an IP address, separately from analytics records, and expire after two hours. We do not maintain a long-term visitor directory. Provider logs and recovery copies have their own lifecycles.</p>
        <p>Applications and contact enquiries are automatically deleted from the live portal within <strong>three calendar months from submission</strong>, calculated in UTC. Deletion may occur a few minutes early. Changing status, archiving, closing a role or setting its start date does not extend this period. There is no hidden talent-pool archive. The owner can delete a submission sooner.</p>
        <p>If recruitment or a conversation needs to continue beyond this period, we must explain any separate, necessary record and its retention to you. Required employment and right-to-work check records are not kept in this recruitment inbox. Provider security logs and restricted disaster-recovery copies have separate lifecycles; they are not an active recruitment archive. We must reapply deletion before returning any restored database to service. Contact us for details of applicable provider retention arrangements.</p>
      </section>

      <section><h2>Who handles your information?</h2>
<p>The company owner is the authorised inbox reviewer and analytics dashboard user. We do not sell personal information or share it for advertising. We use service providers to run the site: Vercel for hosting and processing analytics requests, Supabase for the database (including analytics) and administrator authentication, and Cloudflare for domain/network services. We do not install Google Analytics, advertising pixels or an external session-replay service. Where enabled, our notification-email service, Resend, receives a generic alert to the owner, not your name, email, message, portfolio, permission category or application contents. Interview confirmation emails, when separately enabled, contain the meeting details described above. If you email us directly or we reply by email, our business email provider also processes that correspondence.</p>
        <p>Standard website fonts are served with the site. The Flutter-based main website may request a Google Fonts fallback to display characters not covered by those fonts; Google then receives connection information such as your IP address, not your form contents. These providers and their authorised subprocessors are involved even when only the owner opens your application. We may also disclose information where legally required. The service is not intended for classified defence information.</p>
      </section>

      <section><h2>Location and international processing</h2>
        <p>The primary application database and the website’s server-side application functions are configured in London. This does not mean that every network request, support activity, security log or backup stays in the UK: providers operate international infrastructure.</p>
        <p>International access and transfers require assessment of the particular provider and applicable safeguards, such as UK adequacy regulations or contractual transfer safeguards with any required risk assessment. The providers’ published terms describe their arrangements: <a href="https://vercel.com/legal/dpa" target="_blank" rel="noreferrer">Vercel’s data-processing terms</a> and <a href="https://supabase.com/docs/guides/security/gdpr-compliance" target="_blank" rel="noreferrer">Supabase’s privacy and DPA information</a>. Contact us for details or a copy of safeguards applicable to your data. We do not represent this public website as a certified UK-only defence system.</p>
      </section>

      <section id="privacy-rights"><h2>Your rights and complaints</h2>
        <p><strong>You can withdraw analytics consent at any time through the <a href="#cookie-choices">cookie choices section above</a>.</strong> You can also object to processing based on legitimate interests. For a request concerning analytics already collected, we may not be able to identify which page-view records relate to you because we do not maintain a named visitor profile; we will explain any identification limits rather than collect extra information just to identify you.</p>
        <p>Depending on the circumstances, you can request access, correction, erasure, restriction or a portable copy of your data, and object to processing based on legitimate interests. These rights have legal conditions and exceptions. You can reach us through our <Link href="/contact">contact form</Link>; no account is required. This does not limit your right to make a request by other means. We will ask only for proportionate information if needed to establish your identity.</p>
        <p>We aim to respond without undue delay, normally within one calendar month for a rights request. If a permitted extension applies, we will explain it. We acknowledge data-protection complaints within 30 days, investigate without undue delay and keep you informed of the outcome. You can also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p>
      </section>

      <section><h2>Browser storage and security</h2>
        <p>Optional website analytics is controlled separately from submission of an application or enquiry. The admin area uses browser session storage for essential authentication, which is cleared when the tab session ends, and locks after inactivity. Submission contents are not put into browser storage. Please do not use a shared device for the admin portal. External portfolio links and sites have their own privacy practices.</p>
        <p>We use encrypted connections, restricted server-side access, input checks and automatic expiry. No website or free hosting plan guarantees uninterrupted availability. If a submission cannot be saved, the form reports an error rather than claiming success.</p>
      </section>
      <section><h2>Children, external links and changes</h2><p>This business website is not directed at children under 16. Please contact us if you believe a child has provided information that needs to be removed. Links to work examples, social networks and other external websites lead to services with their own privacy practices.</p><p>We will update this notice when our processing changes and show the latest date above. Historical form and consent versions remain identifiable in the records they accompanied. New optional purposes will require fresh consent where applicable; accepting this notice is not blanket permission for future tracking.</p></section>
    </article>
  </main><SiteFooter /></>
}
