import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  X,
  Plus,
  Minus,
  ArrowCounterClockwise,
  Pause,
  Play,
  Compass,
  GlobeHemisphereWest,
  SquaresFour,
  GraduationCap,
  Buildings,
  Hospital,
  House,
  MusicNotes,
  Train,
  AirplaneTilt,
  Boat,
  Waves,
  CraneTower,
  Snowflake,
  Factory,
  ShieldCheck,
  FirstAidKit,
  Tent,
  Planet,
  Moon,
  Rocket,
  Cube,
  Eye,
  List,
  CaretDown,
} from "@phosphor-icons/react";
const icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  close: X,
  plus: Plus,
  minus: Minus,
  reset: ArrowCounterClockwise,
  pause: Pause,
  play: Play,
  compass: Compass,
  globe: GlobeHemisphereWest,
  grid: SquaresFour,
  school: GraduationCap,
  building: Buildings,
  hospital: Hospital,
  home: House,
  music: MusicNotes,
  train: Train,
  plane: AirplaneTilt,
  ship: Boat,
  waves: Waves,
  rig: CraneTower,
  snow: Snowflake,
  industry: Factory,
  shield: ShieldCheck,
  relief: FirstAidKit,
  tent: Tent,
  planet: Planet,
  moon: Moon,
  station: Rocket,
  cube: Cube,
  eye: Eye,
  menu: List,
  down: CaretDown,
};
export function Icon({ name, size = 20, ...props }) {
  const C = icons[name] || GlobeHemisphereWest;
  return <C size={size} weight="regular" aria-hidden="true" {...props} />;
}
